version: '3.10'
services:
  backend:
    build: ./backend/src
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
  database:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
